item-1: 
  item-name: "minecraft:iron_sword"
  amount: 1
  nbt-tag: "{}"
item-2:
  loot-luck: 10 # pourcents
  item-name: "minecraft:iron_pickaxe"
  amount: 1
  nbt-tag: "{}"
item-3: 
  item-name: "minecraft:iron_axe"
  amount: 1
  nbt-tag: "{}"