entities: # You can add any amount of entities
  entity-1:
    spawn-coordinates: # pitch & yaw are optional
      loc-1: "[World_Dj_EO/-189/5/-26]" # Please use non-decimal numbers.
    entity-type: minecraft:zombie
    # For dongeon-mob-type value, please choose between :
    # ENTITY.MOB for basic mobs
    # ENTITY.BOSS for mid-bosses & bosses
    # ENTITY.WORLDBOSS for worldbosses
    dongeon-mob-type: ENTITY.MOB
    health: 20.0 # Use . instead of , to use decimal-values
    nbt-tag: "{}" # NBT-TAG Like /summon command tag
    inventory:
      armor: 
        helmet: 
          item-name: minecraft:iron_helmet
          amount: 1
          nbt-tag: "{}"
        chestplate:
          item-name: minecraft:diamond_chestplate
          amount: 1
          nbt-tag: "{}"
        leggings:
          item-name: minecraft:iron_leggings
          amount: 1
          nbt-tag: "{}"
        boots: 
          item-name: minecraft:diamond_boots
          amount: 1
          nbt-tag: "{}"
      hands:
        main-hand: 
          item-name: minecraft:diamond_sword
          amount: 1
          nbt-tag: "{}"
        off-hand:
          item-name: minecraft:shield
          amount: 1
          nbt-tag: "{}"